# Generated by Django 3.2.16 on 2022-12-26 20:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sponsor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0026_auto_20170116_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsoring',
            name='gplusAccount',
        ),
        migrations.RemoveField(
            model_name='sponsoring',
            name='gplusAccountOptOut',
        ),
        migrations.RemoveField(
            model_name='sponsoring',
            name='gplusPage',
        ),
        migrations.RemoveField(
            model_name='sponsoring',
            name='gplusPageOptOut',
        ),
        migrations.AddField(
            model_name='sponsoring',
            name='linkedinPage',
            field=models.URLField(blank=True, verbose_name='Linkedin page URL'),
        ),
        migrations.AddField(
            model_name='sponsoring',
            name='linkedinPageOptOut',
            field=models.BooleanField(default=False, verbose_name='Sponsor does not use linkedin page URL'),
        ),
        migrations.AlterField(
            model_name='sponsorcontact',
            name='contactPersonGender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender of contact person'),
        ),
        migrations.AlterField(
            model_name='sponsorcontact',
            name='contactPersonLanguage',
            field=models.CharField(choices=[('de-DE', 'German'), ('en-US', 'English')], default='de-DE', max_length=16, verbose_name='Language of contact person'),
        ),
        migrations.AlterField(
            model_name='sponsorcontact',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.sponsormail', verbose_name='Mail contact template'),
        ),
        migrations.AlterField(
            model_name='sponsoring',
            name='boothBarTables',
            field=models.IntegerField(blank=True, null=True, verbose_name="How many bar tables do you need? Please note that we can only provide tables and don't have bar stools."),
        ),
        migrations.AlterField(
            model_name='sponsoring',
            name='boothChairs',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many chairs do you need?'),
        ),
        migrations.AlterField(
            model_name='sponsoring',
            name='logo',
            field=models.ImageField(blank=True, upload_to=sponsor.models.random_filename_upload_logos, verbose_name='Company logo for homepage (preferably as PNG)'),
        ),
        migrations.AlterField(
            model_name='sponsoring',
            name='programAd',
            field=models.FileField(blank=True, upload_to=sponsor.models.random_filename_upload_ad, verbose_name='PDF of your advertisement in our printed program'),
        ),
        migrations.AlterField(
            model_name='sponsoring',
            name='twitterAccount',
            field=models.CharField(blank=True, max_length=128, verbose_name='Twitter account name'),
        ),
        migrations.AlterField(
            model_name='sponsoring',
            name='vectorLogo',
            field=models.FileField(blank=True, upload_to=sponsor.models.random_filename_upload_vec_logos, verbose_name='Company logo as vector graphics (preferably PDF or SVG) for printed advertisements such as posters, flyers and visitor badges'),
        ),
        migrations.AlterField(
            model_name='sponsoring',
            name='wantBooth',
            field=models.BooleanField(null=True, verbose_name='Do you want a booth for your company on the conference?'),
        ),
        migrations.AlterField(
            model_name='sponsoring',
            name='wantRecruting',
            field=models.BooleanField(null=True, verbose_name='Do you want to participate in the recruiting event on the conference?'),
        ),
        migrations.AlterField(
            model_name='sponsormailattachment',
            name='attachment',
            field=models.FileField(upload_to='sponsormail_attachments', verbose_name='The contact mail attachment'),
        ),
        migrations.AlterField(
            model_name='sponsorpackage',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Please enter a HTML color code of format #[0-9a-f]{6}', regex='#[0-9a-f]{6}')], verbose_name='Display color of sponsor package'),
        ),
    ]
