# Generated by Django 5.1.7 on 2025-03-29 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0027_auto_20221226_2130"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorcontact",
            name="extraContactEmails",
            field=models.TextField(
                blank=True,
                help_text="An empty or comma separated list of additional contact mails",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "([^@]+@[^@]+\\.\\w+,?)+",
                        "Not valid comma separated mails list.",
                    )
                ],
                verbose_name="Further contact mails",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorcontact",
            name="contactPersonGender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("D", "Diverse")],
                max_length=1,
                verbose_name="Gender of contact person",
            ),
        ),
    ]
