# Generated by Django 5.1.7 on 2025-03-29 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0028_sponsorcontact_extracontactemails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorcontact",
            name="extraContactEmails",
            field=models.CharField(
                blank=True,
                help_text="An empty or comma separated list of additional contact mails",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "([^@]+@[^@]+\\.\\w+,?)+",
                        "Not valid comma separated mails list.",
                    )
                ],
                verbose_name="Further contact mails",
            ),
        ),
    ]
