# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 13:53


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConferenceYear",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        editable=False,
                        verbose_name="Conference year that exists in our database",
                    ),
                ),
            ],
        ),
    ]
