# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceyear',
            name='year',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='Conference year that exists in our database'),
        ),
    ]
