# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True)),
                ('modifyDate', models.DateField(auto_now=True)),
                ('projectName', models.CharField(max_length=128, verbose_name='Project name')),
                ('logo', models.ImageField(blank=True, upload_to=b'exhibitors/logos', verbose_name='Project logo')),
                ('homepage', models.URLField(blank=True, verbose_name='Project homepage url')),
                ('descriptionDE', models.TextField(blank=True, verbose_name='Description text of your project (German)')),
                ('descriptionEN', models.TextField(blank=True, verbose_name='Description text of your project (English)')),
                ('boothPreferedLocation', models.PositiveIntegerField(choices=[(1, b'Mensa'), (2, b'First Floor'), (0, b'No preference')], default=0, verbose_name='Do you have a preferred location for your booth?')),
                ('boothNumTables', models.PositiveIntegerField(blank=True, null=True, verbose_name='How many tables do you need (roughly 1.20m x 0.80m)?')),
                ('boothNumChairs', models.PositiveIntegerField(blank=True, null=True, verbose_name='How many chairs do you need?')),
                ('boothComment', models.TextField(blank=True, verbose_name='Here you have the chance to leave us further comments regarding your booth:')),
                ('accepted', models.BooleanField(default=False, editable=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='exhibitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitorParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitor.Exhibitor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='participants',
            field=models.ManyToManyField(blank=True, editable=False, related_name='exhibitorparticipation', through='exhibitor.ExhibitorParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
