# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 13:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitor",
            name="year",
            field=models.PositiveIntegerField(
                default=1,
                editable=False,
                verbose_name="Conference year this exhibitor belongs to",
            ),
            preserve_default=False,
        ),
    ]
