# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 21:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcel", "0002_auto_20160413_2210"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="year",
            field=models.PositiveIntegerField(
                default=1,
                editable=False,
                verbose_name="Conference year this parcel belongs to",
            ),
            preserve_default=False,
        ),
    ]
