# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True)),
                ('modifyDate', models.DateField(auto_now=True)),
                ('projectName', models.CharField(max_length=128, verbose_name='Project name')),
                ('logo', models.ImageField(blank=True, upload_to=b'devrooms/logos', verbose_name='Project logo')),
                ('homepage', models.URLField(blank=True, verbose_name='Project homepage url')),
                ('descriptionDE', models.TextField(blank=True, verbose_name='Description text of your project (German)')),
                ('descriptionEN', models.TextField(blank=True, verbose_name='Description text of your project (English)')),
                ('schedule', models.TextField(blank=True, verbose_name="How long do you want to use the dev room? (e.g. one day/both days/only one afternoom) If you don't want the complete time, do you have a preferred day/time?")),
                ('plannedProgram', models.TextField(blank=True, verbose_name='Give a short description of the program you plan for the Devroom. We will choose the projects based on this description. If you have special requirements, please note this also here.')),
                ('anticipatedGuests', models.PositiveIntegerField(blank=True, null=True, verbose_name="For how many guests is your programme planned? If you don't plan with a fixed number, how many guests do you expect to have? (We use this to plan the room sizes)")),
                ('accepted', models.BooleanField(default=False, editable=False)),
                ('room', models.CharField(blank=True, editable=False, max_length=16)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='devrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevroomParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devroom.Devroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='devroom',
            name='participants',
            field=models.ManyToManyField(blank=True, editable=False, related_name='_devroom_participants_+', through='devroom.DevroomParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
